<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * php artisan db:seed --class=UserSeeder
     */
    public function run()
    {
        $users = [
            [
                'name' => 'Jenelyn Pagalillauan',
                'birthdate' => '1985-05-10',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '09155135666',
                'gender' => 'Female',
                'status' => 'Married',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Secretariat',
                'position' => 'Executive Secretary',
                'designation' => 'Northern Luzon Mission Office Workers',
                'work_status' => 'Contractual',
                'category' => 'Ministerial Credential',
                'img' => null,
                'acc_code' => '1004',
                'reg_approval' => '2025-05-05',
                'email' => 'jen@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Resh Ramos',
                'birthdate' => '1985-05-10',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '9155135666',
                'gender' => 'Female',
                'status' => 'Single',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Accounting Personnel',
                'position' => 'Disbursing Accountant',
                'designation' => 'Northern Luzon Mission Office Workers',
                'work_status' => 'Probationary',
                'category' => 'None',
                'img' => null,
                'acc_code' => '1002',
                'reg_approval' => '2025-05-05',
                'email' => 'resh@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ismael Cabason',
                'birthdate' => '1985-05-10',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '9155135666',
                'gender' => 'Male',
                'status' => 'Married',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Administrators',
                'position' => 'President',
                'designation' => 'Northern Luzon Mission Office Workers',
                'work_status' => 'Ordained',
                'category' => 'Ministerial Licensed',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'icabason@adventist.ph',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Oliver De Vera',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '9053192544',
                'gender' => 'Male',
                'status' => 'Single',
                'address' => 'Artacho Sison Pangasinans',
                'department' => 'Administrators',
                'position' => 'Executive Secretary, Human Resource',
                'designation' => 'Northern Luzon Mission Office Workers',
                'work_status' => 'Regular',
                'category' => 'Ministerial Credential',
                'img' => '1750052088.jpg',
                'acc_code' => '1003',
                'reg_approval' => '2025-05-05',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Miller Payoyo',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '9171296605',
                'gender' => 'Male',
                'status' => 'Married',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Administrator',
                'position' => 'Treasurer',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'mpayoyo@yahoo.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lolita Agdeppa',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Poblacion Norte Sison Pangasinan',
                'phone_number' => '9651628459',
                'gender' => 'Female',
                'status' => 'Married',
                'address' => 'Poblacion Norte Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Women Family Music',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'lolita.agdeppa@gmail.com',
               'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Leonel Diaz',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artcho Sison Pangasinan',
                'phone_number' => '9771700120',
                'gender' => 'Male',
                'status' => 'Married',
                'address' => 'Artcho Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Ministerial, Nurture Discipleship Retention Integrated Evangelion Lifestyle',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'leonel.diaz@example.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jenny Diaz',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artcho Sison Pangasinan',
                'phone_number' => '9072274883',
                'gender' => 'Female',
                'status' => 'Married',
                'address' => 'Artcho Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Education',
                'designation' => 'Northern Luzon Mission Office Workers',
                'work_status' => 'Missionary Volunteer',
                'category' => 'Ministerial Credential',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'jcdiaz@adventist.ph',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Benjamin Dotimas',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artcho Sison Pangasinan',
                'phone_number' => '9153133763',
                'gender' => 'Male',
                'status' => 'Married',
                'address' => 'Artcho Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Communication Ministry, Health Ministry',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'benj_70ph@yahoo.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Noah Hope',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artcho Sison Pangasinan',
                'phone_number' => '9664408814',
                'gender' => 'Male',
                'status' => 'Married',
                'address' => 'Artcho Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Publishing Ministry, Spirit of Prophecy',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2025-05-05',
                'email' => 'noahhope@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'glen lozada',
                'birthdate' => '2001-05-02',
                'birthplace' => 'Agoo La Union',
                'phone_number' => '9610609040',
                'gender' => 'Male',
                'status' => 'Single',
                'address' => 'Agat, Sison, Pangasinan',
                'department' => 'Teachers',
                'position' => 'Teacher',
                'designation' => 'Camiling Adventist School Inc.',
                'work_status' => 'Intern',
                'category' => 'None',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => '2008-02-19',
                'email' => 'glen@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'hanna banana',
                'birthdate' => '2001-12-04',
                'birthplace' => 'agoo',
                'phone_number' => '9454561235',
                'gender' => 'Male',
                'status' => 'Single',
                'address' => 'sagunto',
                'department' => 'Teachers',
                'position' => 'Teacher',
                'designation' => 'Rodrigo Agustin Fernando Memorial Adv. School',
                'work_status' => 'Intern',
                'category' => 'None',
                'img' => '1747702638.jpg',
                'acc_code' => null,
                'reg_approval' => '2025-05-20',
                'email' => 'hanna@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Felipe Manlongat Jr.',
                'birthdate' => '1992-08-21',
                'birthplace' => 'Artcho Sison Pangasinan',
                'phone_number' => '09338593143',
                'gender' => 'male',
                'status' => 'Married',
                'address' => 'Artcho Sison Pangasinan',
                'department' => 'Directors',
                'position' => 'Youth Ministries',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'Part-time',
                'category' => 'Staff',
                'img' => null,
                'acc_code' => null,
                'reg_approval' => Carbon::now(),
                'email' => 'fmanlungatjr@yahoo.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // Insert the users into the database
        User::insert($users);
    }
}