<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * php artisan db:seed --class=UserSeeder
     */
    public function run()
    {
        $users = [
            [
                'name' => 'Jenelyn Pagalillauan',
                'birthdate' => '1985-05-10',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '09155135666',
                'gender' => 'Female',
                'status' => 'Married',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Secrtariat',
                'position' => 'Executive Secretary',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'regular',
                'category' => 'Admin',
                'img' => null,
                'reg_approval' => Carbon::now(),
                'email' => 'jen@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Resh Ramos',
                'birthdate' => '1985-05-10',
                'birthplace' => 'Artacho Sison Pangasinan',
                'phone_number' => '09155135666',
                'gender' => 'Female',
                'status' => 'Single',
                'address' => 'Artacho Sison Pangasinan',
                'department' => 'Accounting Peqsonnel',
                'position' => 'Disbursing Accountant',
                'designation' => 'Northern Luzon Mission Office Worker',
                'work_status' => 'regular',
                'category' => 'Admin',
                'img' => null,
                'reg_approval' => Carbon::now(),
                'email' => 'resh@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // [
            //     'name' => 'Ismael Cabason',
            //     'birthdate' => '1985-05-10',
            //     'birthplace' => 'Artacho Sison Pangasinan',
            //     'phone_number' => '09155135666',
            //     'gender' => 'male',
            //     'status' => 'Married',
            //     'address' => 'Artacho Sison Pangasinan',
            //     'department' => 'Administrator',
            //     'position' => 'President',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'regular',
            //     'category' => 'Admin',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'icabason@adventist.ph',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Oliver De Vera',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artacho Sison Pangasinan',
            //     'phone_number' => '09053192544',
            //     'gender' => 'Male',
            //     'status' => 'Married',
            //     'address' => 'Artacho Sison Pangasinan',
            //     'department' => 'Administrator',
            //     'position' => 'Executive Secretary',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'bob@example.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Miller Payoyo',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artacho Sison Pangasinan',
            //     'phone_number' => '09171296605',
            //     'gender' => 'Male',
            //     'status' => 'Married',
            //     'address' => 'Artacho Sison Pangasinan',
            //     'department' => 'Administrator',
            //     'position' => 'Treasurer',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'mpayoyo@yahoo.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Lolita Agdeppa',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Poblacion Norte Sison Pangasinan',
            //     'phone_number' => '09651628459',
            //     'gender' => 'Female',
            //     'status' => 'Married',
            //     'address' => 'Poblacion Norte Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Women Family Music',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'lolita.agdeppa@gmail.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Leonel Diaz',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artcho Sison Pangasinan',
            //     'phone_number' => '09771700120',
            //     'gender' => 'Male',
            //     'status' => 'Married',
            //     'address' => 'Artcho Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Ministerial, Nurture Discipleship Retention Integrated Evangelion Lifestyle',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'leonel.diaz@example.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Jenny Diaz',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artcho Sison Pangasinan',
            //     'phone_number' => '09072274883',
            //     'gender' => 'Female',
            //     'status' => 'Married',
            //     'address' => 'Artcho Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Adventist Children Ministry, Adventist Possibility Ministry, Education, Ministerial Spouse Association',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'jcdiaz@adventist.ph',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Benjamin Dotimas',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artcho Sison Pangasinan',
            //     'phone_number' => '09153133763',
            //     'gender' => 'male',
            //     'status' => 'Married',
            //     'address' => 'Artcho Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Communication Ministry, Health Ministry',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'benj_70ph@yahoo.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Noah Hope',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artcho Sison Pangasinan',
            //     'phone_number' => '09664408814',
            //     'gender' => 'male',
            //     'status' => 'Married',
            //     'address' => 'Artcho Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Publishing Ministry, Spirit of Prophecy',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'noahhope@gmail.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'name' => 'Felipe Manlongat Jr.',
            //     'birthdate' => '1992-08-21',
            //     'birthplace' => 'Artcho Sison Pangasinan',
            //     'phone_number' => '09338593143',
            //     'gender' => 'male',
            //     'status' => 'Married',
            //     'address' => 'Artcho Sison Pangasinan',
            //     'department' => 'Directors',
            //     'position' => 'Youth Ministries',
            //     'designation' => 'Northern Luzon Mission Office Worker',
            //     'work_status' => 'Part-time',
            //     'category' => 'Staff',
            //     'img' => null,
            //     'reg_approval' => Carbon::now(),
            //     'email' => 'fmanlungatjr@yahoo.com',
            //     'email_verified_at' => Carbon::now(),
            //     'password' => Hash::make('password123'),
            //     'remember_token' => Str::random(10),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ]
        ];

        // Insert the users into the database
        User::insert($users);
    }
}